// Cian metro map snapshot, 2026-09-20. See docs/cian-research.md.
export const metroStations: { region: string; name: string; color: string; ids: number[] }[] = [
  {
    region: '1',
    name: 'Авиамоторная',
    color: '#d96835',
    ids: [472, 443, 1],
  },
  {
    region: '4777',
    name: 'Авиастроительная',
    color: '#cf0000',
    ids: [313],
  },
  {
    region: '2',
    name: 'Автово',
    color: '#cf0000',
    ids: [183],
  },
  {
    region: '1',
    name: 'Автозаводская',
    color: '#ffc8c8',
    ids: [2],
  },
  {
    region: '2',
    name: 'Адмиралтейская',
    color: '#94007c',
    ids: [242],
  },
  {
    region: '1',
    name: 'Академическая',
    color: '#ef7e24',
    ids: [3],
  },
  {
    region: '2',
    name: 'Академическая',
    color: '#cf0000',
    ids: [169],
  },
  {
    region: '1',
    name: 'Александровский сад',
    color: '#24bcef',
    ids: [4],
  },
  {
    region: '1',
    name: 'Алексеевская',
    color: '#ef7e24',
    ids: [5],
  },
  {
    region: '1',
    name: 'Алма-Атинская',
    color: '#4baf4f',
    ids: [245],
  },
  {
    region: '1',
    name: 'Алтуфьево',
    color: '#adacac',
    ids: [6],
  },
  {
    region: '4777',
    name: 'Аметьево',
    color: '#cf0000',
    ids: [320],
  },
  {
    region: '1',
    name: 'Аминьевская',
    color: '#78c7c9',
    ids: [392, 507],
  },
  {
    region: '1',
    name: 'Андроновка',
    color: '#d96835',
    ids: [473, 302],
  },
  {
    region: '1',
    name: 'Аникеевка',
    color: '#f2bbe6',
    ids: [416],
  },
  {
    region: '1',
    name: 'Аннино',
    color: '#adacac',
    ids: [7],
  },
  {
    region: '1',
    name: 'Апрелевка',
    color: '#41b384',
    ids: [494],
  },
  {
    region: '1',
    name: 'Арбатская',
    color: '#24bcef',
    ids: [8],
  },
  {
    region: '1',
    name: 'Аэропорт',
    color: '#4baf4f',
    ids: [9],
  },
  {
    region: '1',
    name: 'Аэропорт Внуково',
    color: '#ffcd1e',
    ids: [535],
  },
  {
    region: '1',
    name: 'Бабушкинская',
    color: '#ef7e24',
    ids: [10],
  },
  {
    region: '1',
    name: 'Багратионовская',
    color: '#24bcef',
    ids: [11],
  },
  {
    region: '1',
    name: 'Баковка',
    color: '#ffcd6f',
    ids: [405],
  },
  {
    region: '1',
    name: 'Балтийская',
    color: '#ffc8c8',
    ids: [293],
  },
  {
    region: '2',
    name: 'Балтийская',
    color: '#cf0000',
    ids: [180],
  },
  {
    region: '1',
    name: 'Баррикадная',
    color: '#943f90',
    ids: [12],
  },
  {
    region: '1',
    name: 'Бауманская',
    color: '#0572b9',
    ids: [13],
  },
  {
    region: '1',
    name: 'Бачуринская',
    color: '#33735e',
    ids: [544],
  },
  {
    region: '1',
    name: 'Беговая',
    color: '#ffcd6f',
    ids: [14],
  },
  {
    region: '2',
    name: 'Беговая',
    color: '#00701a',
    ids: [355],
  },
  {
    region: '1',
    name: 'Белокаменная',
    color: '#ffc8c8',
    ids: [298],
  },
  {
    region: '1',
    name: 'Беломорская',
    color: '#4baf4f',
    ids: [369],
  },
  {
    region: '1',
    name: 'Белорусская',
    color: '#ffcd6f',
    ids: [15, 514],
  },
  {
    region: '1',
    name: 'Беляево',
    color: '#ef7e24',
    ids: [16],
  },
  {
    region: '1',
    name: 'Бескудниково',
    color: '#ffcd6f',
    ids: [413],
  },
  {
    region: '1',
    name: 'Бибирево',
    color: '#adacac',
    ids: [17],
  },
  {
    region: '1',
    name: 'Библиотека им. Ленина',
    color: '#e42518',
    ids: [18],
  },
  {
    region: '1',
    name: 'Битца',
    color: '#f2bbe6',
    ids: [433],
  },
  {
    region: '1',
    name: 'Битцевский парк',
    color: '#bac8e8',
    ids: [274],
  },
  {
    region: '1',
    name: 'Борисово',
    color: '#bed12e',
    ids: [240],
  },
  {
    region: '1',
    name: 'Боровицкая',
    color: '#adacac',
    ids: [20],
  },
  {
    region: '1',
    name: 'Боровское шоссе',
    color: '#ffcd1e',
    ids: [365],
  },
  {
    region: '1',
    name: 'Ботанический сад',
    color: '#ffc8c8',
    ids: [21],
  },
  {
    region: '1',
    name: 'Братиславская',
    color: '#bed12e',
    ids: [22],
  },
  {
    region: '1',
    name: 'Бульвар Адмирала Ушакова',
    color: '#bac8e8',
    ids: [23],
  },
  {
    region: '1',
    name: 'Бульвар Дмитрия Донского',
    color: '#adacac',
    ids: [24],
  },
  {
    region: '1',
    name: 'Бульвар Карбышева',
    color: '#273040',
    ids: [558],
  },
  {
    region: '1',
    name: 'Бульвар Рокоссовского',
    color: '#ffc8c8',
    ids: [137],
  },
  {
    region: '1',
    name: 'Бунинская аллея',
    color: '#bac8e8',
    ids: [25],
  },
  {
    region: '1',
    name: 'Бутово',
    color: '#f2bbe6',
    ids: [437],
  },
  {
    region: '1',
    name: 'Бутырская',
    color: '#bed12e',
    ids: [287],
  },
  {
    region: '2',
    name: 'Бухарестская',
    color: '#94007c',
    ids: [247],
  },
  {
    region: '1',
    name: 'Быково',
    color: '#d96835',
    ids: [486],
  },
  {
    region: '1',
    name: 'Вавиловская',
    color: '#33735e',
    ids: [541],
  },
  {
    region: '1',
    name: 'Варшавская',
    color: '#78c7c9',
    ids: [26],
  },
  {
    region: '2',
    name: 'Василеостровская',
    color: '#00701a',
    ids: [205],
  },
  {
    region: '1',
    name: 'ВДНХ',
    color: '#ef7e24',
    ids: [27],
  },
  {
    region: '1',
    name: 'Верхние Котлы',
    color: '#ffc8c8',
    ids: [307],
  },
  {
    region: '1',
    name: 'Верхние Лихоборы',
    color: '#bed12e',
    ids: [353],
  },
  {
    region: '1',
    name: 'Вешняки',
    color: '#d96835',
    ids: [476],
  },
  {
    region: '2',
    name: 'Владимирская',
    color: '#cf0000',
    ids: [177],
  },
  {
    region: '1',
    name: 'Владыкино',
    color: '#ffc8c8',
    ids: [28],
  },
  {
    region: '1',
    name: 'Внуково',
    color: '#41b384',
    ids: [501],
  },
  {
    region: '1',
    name: 'Водники',
    color: '#ffcd6f',
    ids: [409],
  },
  {
    region: '1',
    name: 'Водный стадион',
    color: '#4baf4f',
    ids: [29],
  },
  {
    region: '1',
    name: 'Войковская',
    color: '#4baf4f',
    ids: [30],
  },
  {
    region: '1',
    name: 'Волгоградский проспект',
    color: '#943f90',
    ids: [31],
  },
  {
    region: '1',
    name: 'Волжская',
    color: '#bed12e',
    ids: [32],
  },
  {
    region: '2',
    name: 'Волковская',
    color: '#94007c',
    ids: [230],
  },
  {
    region: '1',
    name: 'Волоколамская',
    color: '#f2bbe6',
    ids: [234],
  },
  {
    region: '1',
    name: 'Воробьёвы горы',
    color: '#e42518',
    ids: [33],
  },
  {
    region: '1',
    name: 'Воронцовская',
    color: '#78c7c9',
    ids: [390],
  },
  {
    region: '2',
    name: 'Выборгская',
    color: '#cf0000',
    ids: [173],
  },
  {
    region: '1',
    name: 'Выставочная',
    color: '#24bcef',
    ids: [35],
  },
  {
    region: '1',
    name: 'Выставочный центр',
    color: '#0a72b9',
    ids: [277],
  },
  {
    region: '1',
    name: 'Выхино',
    color: '#d96835',
    ids: [477, 34],
  },
  {
    region: '1',
    name: 'Генерала Тюленева',
    color: '#33735e',
    ids: [550],
  },
  {
    region: '1',
    name: 'Говорово',
    color: '#ffcd1e',
    ids: [363],
  },
  {
    region: '4777',
    name: 'Горки',
    color: '#cf0000',
    ids: [321],
  },
  {
    region: '2',
    name: 'Горный институт',
    color: '#ff7f00',
    ids: [382],
  },
  {
    region: '2',
    name: 'Горьковская',
    color: '#03238b',
    ids: [193],
  },
  {
    region: '2',
    name: 'Гостиный Двор',
    color: '#00701a',
    ids: [206],
  },
  {
    region: '1',
    name: 'Гражданская',
    color: '#f2bbe6',
    ids: [424],
  },
  {
    region: '2',
    name: 'Гражданский проспект',
    color: '#cf0000',
    ids: [168],
  },
  {
    region: '1',
    name: 'Грачёвская',
    color: '#d96835',
    ids: [464],
  },
  {
    region: '1',
    name: 'Давыдково',
    color: '#78c7c9',
    ids: [393],
  },
  {
    region: '2',
    name: 'Девяткино',
    color: '#cf0000',
    ids: [167],
  },
  {
    region: '1',
    name: 'Дегунино',
    color: '#ffcd6f',
    ids: [414],
  },
  {
    region: '1',
    name: 'Деловой центр',
    color: '#78c7c9',
    ids: [444],
  },
  {
    region: '1',
    name: 'Деловой центр МЦК',
    color: '#ffc8c8',
    ids: [272],
  },
  {
    region: '1',
    name: 'Депо',
    color: '#f2bbe6',
    ids: [428],
  },
  {
    region: '1',
    name: 'Динамо',
    color: '#4baf4f',
    ids: [36],
  },
  {
    region: '1',
    name: 'Дмитровская',
    color: '#f2bbe6',
    ids: [37],
  },
  {
    region: '1',
    name: 'Добрынинская',
    color: '#925233',
    ids: [38],
  },
  {
    region: '1',
    name: 'Долгопрудная',
    color: '#ffcd6f',
    ids: [410],
  },
  {
    region: '1',
    name: 'Домодедовская',
    color: '#4baf4f',
    ids: [39],
  },
  {
    region: '1',
    name: 'Достоевская',
    color: '#bed12e',
    ids: [237],
  },
  {
    region: '2',
    name: 'Достоевская',
    color: '#ff7f00',
    ids: [221],
  },
  {
    region: '1',
    name: 'Дубровка',
    color: '#ffc8c8',
    ids: [40],
  },
  {
    region: '2',
    name: 'Дунайская',
    color: '#94007c',
    ids: [358],
  },
  {
    region: '2',
    name: 'Елизаровская',
    color: '#00701a',
    ids: [210],
  },
  {
    region: '1',
    name: 'Есенинская',
    color: '#d96835',
    ids: [490],
  },
  {
    region: '1',
    name: 'Железнодорожная',
    color: '#41b384',
    ids: [530],
  },
  {
    region: '1',
    name: 'Жулебино',
    color: '#943f90',
    ids: [270],
  },
  {
    region: '2',
    name: 'Звездная',
    color: '#03238b',
    ids: [202],
  },
  {
    region: '1',
    name: 'Звенигородская',
    color: '#273040',
    ids: [560],
  },
  {
    region: '2',
    name: 'Звенигородская',
    color: '#94007c',
    ids: [231],
  },
  {
    region: '1',
    name: 'Зеленоград — Крюково',
    color: '#d96835',
    ids: [455],
  },
  {
    region: '1',
    name: 'ЗИЛ',
    color: '#ffc8c8',
    ids: [306, 556],
  },
  {
    region: '1',
    name: 'Зорге',
    color: '#ffc8c8',
    ids: [290],
  },
  {
    region: '1',
    name: 'Зюзино',
    color: '#78c7c9',
    ids: [389],
  },
  {
    region: '1',
    name: 'Зябликово',
    color: '#bed12e',
    ids: [239],
  },
  {
    region: '1',
    name: 'Измайлово',
    color: '#ffc8c8',
    ids: [300],
  },
  {
    region: '1',
    name: 'Измайловская',
    color: '#0572b9',
    ids: [41],
  },
  {
    region: '1',
    name: 'Ильинская',
    color: '#d96835',
    ids: [487],
  },
  {
    region: '1',
    name: 'Ипподром',
    color: '#d96835',
    ids: [493],
  },
  {
    region: '1',
    name: 'Калитники',
    color: '#f2bbe6',
    ids: [426],
  },
  {
    region: '1',
    name: 'Калужская',
    color: '#ef7e24',
    ids: [42],
  },
  {
    region: '1',
    name: 'Кантемировская',
    color: '#4baf4f',
    ids: [43],
  },
  {
    region: '1',
    name: 'Каховская',
    color: '#78c7c9',
    ids: [44],
  },
  {
    region: '1',
    name: 'Каширская',
    color: '#78c7c9',
    ids: [445, 45],
  },
  {
    region: '1',
    name: 'Киевская',
    color: '#24bcef',
    ids: [46],
  },
  {
    region: '2',
    name: 'Кировский завод',
    color: '#cf0000',
    ids: [182],
  },
  {
    region: '1',
    name: 'Китай-город',
    color: '#943f90',
    ids: [47],
  },
  {
    region: '1',
    name: 'Кленовый бульвар',
    color: '#78c7c9',
    ids: [387],
  },
  {
    region: '1',
    name: 'Кожуховская',
    color: '#bed12e',
    ids: [48],
  },
  {
    region: '4777',
    name: 'Козья слобода',
    color: '#cf0000',
    ids: [316],
  },
  {
    region: '1',
    name: 'Кокошкино',
    color: '#41b384',
    ids: [498],
  },
  {
    region: '1',
    name: 'Коломенская',
    color: '#4baf4f',
    ids: [49],
  },
  {
    region: '2',
    name: 'Комендантский проспект',
    color: '#94007c',
    ids: [215],
  },
  {
    region: '1',
    name: 'Коммунарка',
    color: '#e42518',
    ids: [380, 557],
  },
  {
    region: '1',
    name: 'Комсомольская',
    color: '#e42518',
    ids: [50],
  },
  {
    region: '1',
    name: 'Коньково',
    color: '#ef7e24',
    ids: [51],
  },
  {
    region: '1',
    name: 'Коптево',
    color: '#ffc8c8',
    ids: [294],
  },
  {
    region: '1',
    name: 'Корниловская',
    color: '#33735e',
    ids: [545],
  },
  {
    region: '1',
    name: 'Косино',
    color: '#d96835',
    ids: [478, 370],
  },
  {
    region: '1',
    name: 'Котельники',
    color: '#943f90',
    ids: [282],
  },
  {
    region: '1',
    name: 'Красково',
    color: '#d96835',
    ids: [483],
  },
  {
    region: '1',
    name: 'Красногвардейская',
    color: '#4baf4f',
    ids: [52],
  },
  {
    region: '1',
    name: 'Красногорская',
    color: '#f2bbe6',
    ids: [418],
  },
  {
    region: '1',
    name: 'Краснопресненская',
    color: '#925233',
    ids: [159],
  },
  {
    region: '1',
    name: 'Красносельская',
    color: '#e42518',
    ids: [53],
  },
  {
    region: '1',
    name: 'Красные Ворота',
    color: '#e42518',
    ids: [54],
  },
  {
    region: '1',
    name: 'Красный Балтиец',
    color: '#f2bbe6',
    ids: [423],
  },
  {
    region: '1',
    name: 'Красный строитель',
    color: '#f2bbe6',
    ids: [432],
  },
  {
    region: '1',
    name: 'Кратово',
    color: '#d96835',
    ids: [489],
  },
  {
    region: '1',
    name: 'Крёкшино',
    color: '#41b384',
    ids: [496],
  },
  {
    region: '4777',
    name: 'Кремлёвская',
    color: '#cf0000',
    ids: [317],
  },
  {
    region: '2',
    name: 'Крестовский остров',
    color: '#94007c',
    ids: [217],
  },
  {
    region: '1',
    name: 'Крестьянская Застава',
    color: '#bed12e',
    ids: [55],
  },
  {
    region: '1',
    name: 'Кропоткинская',
    color: '#e42518',
    ids: [56],
  },
  {
    region: '1',
    name: 'Крылатское',
    color: '#0572b9',
    ids: [57],
  },
  {
    region: '1',
    name: 'Крымская',
    color: '#ffc8c8',
    ids: [308, 554],
  },
  {
    region: '1',
    name: 'Кузнецкий Мост',
    color: '#943f90',
    ids: [58],
  },
  {
    region: '1',
    name: 'Кузьминки',
    color: '#943f90',
    ids: [59],
  },
  {
    region: '1',
    name: 'Кунцевская',
    color: '#ffcd6f',
    ids: [60, 394],
  },
  {
    region: '2',
    name: 'Купчино',
    color: '#03238b',
    ids: [203],
  },
  {
    region: '1',
    name: 'Курская',
    color: '#f2bbe6',
    ids: [61, 519],
  },
  {
    region: '1',
    name: 'Курьяново',
    color: '#f2bbe6',
    ids: [439],
  },
  {
    region: '1',
    name: 'Кусково',
    color: '#41b384',
    ids: [523],
  },
  {
    region: '1',
    name: 'Кутузовская',
    color: '#ffc8c8',
    ids: [62, 511],
  },
  {
    region: '1',
    name: 'Кучино',
    color: '#41b384',
    ids: [528],
  },
  {
    region: '2',
    name: 'Ладожская',
    color: '#ff7f00',
    ids: [225],
  },
  {
    region: '1',
    name: 'Левобережная',
    color: '#d96835',
    ids: [462],
  },
  {
    region: '1',
    name: 'Ленинский проспект',
    color: '#ef7e24',
    ids: [63],
  },
  {
    region: '2',
    name: 'Ленинский проспект',
    color: '#cf0000',
    ids: [184],
  },
  {
    region: '1',
    name: 'Лермонтовский проспект',
    color: '#943f90',
    ids: [271],
  },
  {
    region: '2',
    name: 'Лесная',
    color: '#cf0000',
    ids: [172],
  },
  {
    region: '1',
    name: 'Лесной Городок',
    color: '#41b384',
    ids: [500],
  },
  {
    region: '1',
    name: 'Лесопарковая',
    color: '#bac8e8',
    ids: [273],
  },
  {
    region: '1',
    name: 'Лефортово',
    color: '#78c7c9',
    ids: [446],
  },
  {
    region: '1',
    name: 'Лианозово',
    color: '#ffcd6f',
    ids: [399, 534],
  },
  {
    region: '2',
    name: 'Лиговский проспект',
    color: '#ff7f00',
    ids: [222],
  },
  {
    region: '1',
    name: 'Лихоборы',
    color: '#d96835',
    ids: [466, 295],
  },
  {
    region: '1',
    name: 'Лобня',
    color: '#ffcd6f',
    ids: [407],
  },
  {
    region: '1',
    name: 'Локомотив',
    color: '#ffc8c8',
    ids: [299],
  },
  {
    region: '2',
    name: 'Ломоносовская',
    color: '#00701a',
    ids: [211],
  },
  {
    region: '1',
    name: 'Ломоносовский проспект',
    color: '#ffcd1e',
    ids: [338],
  },
  {
    region: '1',
    name: 'Лубянка',
    color: '#e42518',
    ids: [64],
  },
  {
    region: '1',
    name: 'Лужники',
    color: '#ffc8c8',
    ids: [310],
  },
  {
    region: '1',
    name: 'Лухмановская',
    color: '#d68ab1',
    ids: [372],
  },
  {
    region: '1',
    name: 'Люберцы',
    color: '#d96835',
    ids: [480],
  },
  {
    region: '1',
    name: 'Люблино',
    color: '#f2bbe6',
    ids: [427, 65],
  },
  {
    region: '1',
    name: 'Малаховка',
    color: '#d96835',
    ids: [484],
  },
  {
    region: '1',
    name: 'Марк',
    color: '#ffcd6f',
    ids: [412],
  },
  {
    region: '1',
    name: 'Марксистская',
    color: '#ffcd1e',
    ids: [66],
  },
  {
    region: '1',
    name: 'Марьина Роща',
    color: '#f2bbe6',
    ids: [537, 454, 236, 516],
  },
  {
    region: '1',
    name: 'Марьино',
    color: '#bed12e',
    ids: [67],
  },
  {
    region: '1',
    name: 'Матвеевская',
    color: '#41b384',
    ids: [508],
  },
  {
    region: '1',
    name: 'Маяковская',
    color: '#4baf4f',
    ids: [68],
  },
  {
    region: '2',
    name: 'Маяковская',
    color: '#00701a',
    ids: [207],
  },
  {
    region: '1',
    name: 'Медведково',
    color: '#ef7e24',
    ids: [69],
  },
  {
    region: '1',
    name: 'Международная',
    color: '#24bcef',
    ids: [70],
  },
  {
    region: '2',
    name: 'Международная',
    color: '#94007c',
    ids: [246],
  },
  {
    region: '1',
    name: 'Менделеевская',
    color: '#adacac',
    ids: [71],
  },
  {
    region: '1',
    name: 'Мещерская',
    color: '#41b384',
    ids: [505],
  },
  {
    region: '1',
    name: 'Минская',
    color: '#ffcd1e',
    ids: [337, 509],
  },
  {
    region: '1',
    name: 'Митино',
    color: '#0572b9',
    ids: [235],
  },
  {
    region: '1',
    name: 'Мичуринец',
    color: '#41b384',
    ids: [502],
  },
  {
    region: '1',
    name: 'Мичуринский проспект',
    color: '#78c7c9',
    ids: [447, 361],
  },
  {
    region: '1',
    name: 'Мнёвники',
    color: '#78c7c9',
    ids: [395],
  },
  {
    region: '1',
    name: 'Молжаниново',
    color: '#d96835',
    ids: [460],
  },
  {
    region: '1',
    name: 'Молодёжная',
    color: '#0572b9',
    ids: [72],
  },
  {
    region: '1',
    name: 'Москва Товарная',
    color: '#f2bbe6',
    ids: [425],
  },
  {
    region: '1',
    name: 'Москворечье',
    color: '#f2bbe6',
    ids: [430],
  },
  {
    region: '2',
    name: 'Московская',
    color: '#03238b',
    ids: [201],
  },
  {
    region: '2',
    name: 'Московские Ворота',
    color: '#03238b',
    ids: [198],
  },
  {
    region: '1',
    name: 'Моссельмаш',
    color: '#d96835',
    ids: [465],
  },
  {
    region: '1',
    name: 'Мякинино',
    color: '#0572b9',
    ids: [233],
  },
  {
    region: '1',
    name: 'Нагатинская',
    color: '#adacac',
    ids: [73],
  },
  {
    region: '1',
    name: 'Нагатинский затон',
    color: '#78c7c9',
    ids: [388],
  },
  {
    region: '1',
    name: 'Нагорная',
    color: '#adacac',
    ids: [74],
  },
  {
    region: '2',
    name: 'Нарвская',
    color: '#cf0000',
    ids: [181],
  },
  {
    region: '1',
    name: 'Народное Ополчение',
    color: '#78c7c9',
    ids: [440],
  },
  {
    region: '1',
    name: 'Нахабино',
    color: '#f2bbe6',
    ids: [415],
  },
  {
    region: '1',
    name: 'Нахимовский проспект',
    color: '#adacac',
    ids: [75],
  },
  {
    region: '2',
    name: 'Невский проспект',
    color: '#03238b',
    ids: [194],
  },
  {
    region: '1',
    name: 'Некрасовка',
    color: '#d68ab1',
    ids: [373],
  },
  {
    region: '1',
    name: 'Немчиновка',
    color: '#ffcd6f',
    ids: [403],
  },
  {
    region: '1',
    name: 'Нижегородская',
    color: '#d68ab1',
    ids: [303, 448, 521],
  },
  {
    region: '1',
    name: 'Никольское',
    color: '#41b384',
    ids: [526],
  },
  {
    region: '1',
    name: 'Новаторская',
    color: '#78c7c9',
    ids: [391, 548],
  },
  {
    region: '1',
    name: 'Новогиреево',
    color: '#ffcd1e',
    ids: [76, 524],
  },
  {
    region: '1',
    name: 'Новодачная',
    color: '#ffcd6f',
    ids: [411],
  },
  {
    region: '1',
    name: 'Новокосино',
    color: '#ffcd1e',
    ids: [243],
  },
  {
    region: '2',
    name: 'Новокрестовская',
    color: '#00701a',
    ids: [356],
  },
  {
    region: '1',
    name: 'Новокузнецкая',
    color: '#4baf4f',
    ids: [77],
  },
  {
    region: '1',
    name: 'Новопеределкино',
    color: '#ffcd1e',
    ids: [366, 532],
  },
  {
    region: '1',
    name: 'Новоподрезково',
    color: '#d96835',
    ids: [459],
  },
  {
    region: '1',
    name: 'Новослободская',
    color: '#925233',
    ids: [78],
  },
  {
    region: '1',
    name: 'Новохохловская',
    color: '#f2bbe6',
    ids: [304],
  },
  {
    region: '2',
    name: 'Новочеркасская',
    color: '#ff7f00',
    ids: [224],
  },
  {
    region: '1',
    name: 'Новоясеневская',
    color: '#ef7e24',
    ids: [19],
  },
  {
    region: '1',
    name: 'Новые Черёмушки',
    color: '#ef7e24',
    ids: [79],
  },
  {
    region: '2',
    name: 'Обводный канал',
    color: '#94007c',
    ids: [241],
  },
  {
    region: '2',
    name: 'Обухово',
    color: '#00701a',
    ids: [213],
  },
  {
    region: '1',
    name: 'Одинцово',
    color: '#ffcd6f',
    ids: [406],
  },
  {
    region: '2',
    name: 'Озерки',
    color: '#03238b',
    ids: [188],
  },
  {
    region: '1',
    name: 'Озёрная',
    color: '#ffcd1e',
    ids: [362],
  },
  {
    region: '1',
    name: 'Окружная',
    color: '#ffcd6f',
    ids: [296],
  },
  {
    region: '1',
    name: 'Окская',
    color: '#d68ab1',
    ids: [375],
  },
  {
    region: '1',
    name: 'Октябрьская',
    color: '#925233',
    ids: [80],
  },
  {
    region: '1',
    name: 'Октябрьское Поле',
    color: '#943f90',
    ids: [81],
  },
  {
    region: '1',
    name: 'Ольгино',
    color: '#41b384',
    ids: [529],
  },
  {
    region: '1',
    name: 'Ольховая',
    color: '#e42518',
    ids: [379],
  },
  {
    region: '1',
    name: 'Опалиха',
    color: '#f2bbe6',
    ids: [417],
  },
  {
    region: '1',
    name: 'Орехово',
    color: '#4baf4f',
    ids: [82],
  },
  {
    region: '1',
    name: 'Останкино',
    color: '#d96835',
    ids: [468],
  },
  {
    region: '1',
    name: 'Остафьево',
    color: '#f2bbe6',
    ids: [438],
  },
  {
    region: '1',
    name: 'Отдых',
    color: '#d96835',
    ids: [488],
  },
  {
    region: '1',
    name: 'Отрадное',
    color: '#adacac',
    ids: [83],
  },
  {
    region: '1',
    name: 'Охотный ряд',
    color: '#e42518',
    ids: [84],
  },
  {
    region: '1',
    name: 'Очаково',
    color: '#41b384',
    ids: [506],
  },
  {
    region: '1',
    name: 'Павелецкая',
    color: '#925233',
    ids: [85],
  },
  {
    region: '1',
    name: 'Павшино',
    color: '#f2bbe6',
    ids: [419],
  },
  {
    region: '1',
    name: 'Панки',
    color: '#d96835',
    ids: [481],
  },
  {
    region: '1',
    name: 'Панфиловская',
    color: '#ffc8c8',
    ids: [291],
  },
  {
    region: '1',
    name: 'Парк культуры',
    color: '#e42518',
    ids: [86],
  },
  {
    region: '1',
    name: 'Парк Победы',
    color: '#ffcd1e',
    ids: [87],
  },
  {
    region: '2',
    name: 'Парк Победы',
    color: '#03238b',
    ids: [200],
  },
  {
    region: '2',
    name: 'Парнас',
    color: '#03238b',
    ids: [186],
  },
  {
    region: '1',
    name: 'Партизанская',
    color: '#0572b9',
    ids: [88],
  },
  {
    region: '1',
    name: 'Пенягино',
    color: '#f2bbe6',
    ids: [420],
  },
  {
    region: '1',
    name: 'Первомайская',
    color: '#0572b9',
    ids: [89],
  },
  {
    region: '1',
    name: 'Переделкино',
    color: '#41b384',
    ids: [503],
  },
  {
    region: '1',
    name: 'Перерва',
    color: '#f2bbe6',
    ids: [429],
  },
  {
    region: '1',
    name: 'Перово',
    color: '#d96835',
    ids: [474, 90],
  },
  {
    region: '1',
    name: 'Петровский парк',
    color: '#78c7c9',
    ids: [350],
  },
  {
    region: '1',
    name: 'Петровско-Разумовская',
    color: '#d96835',
    ids: [467, 91],
  },
  {
    region: '2',
    name: 'Петроградская',
    color: '#03238b',
    ids: [192],
  },
  {
    region: '1',
    name: 'Печатники',
    color: '#f2bbe6',
    ids: [92, 449],
  },
  {
    region: '1',
    name: 'Пионерская',
    color: '#24bcef',
    ids: [93],
  },
  {
    region: '2',
    name: 'Пионерская',
    color: '#03238b',
    ids: [190],
  },
  {
    region: '1',
    name: 'Планерная',
    color: '#943f90',
    ids: [94],
  },
  {
    region: '2',
    name: 'Площадь Александра Невского',
    color: '#00701a',
    ids: [208],
  },
  {
    region: '2',
    name: 'Площадь Восстания',
    color: '#cf0000',
    ids: [176],
  },
  {
    region: '1',
    name: 'Площадь Гагарина',
    color: '#ffc8c8',
    ids: [309],
  },
  {
    region: '1',
    name: 'Площадь Ильича',
    color: '#ffcd1e',
    ids: [95],
  },
  {
    region: '2',
    name: 'Площадь Ленина',
    color: '#cf0000',
    ids: [174],
  },
  {
    region: '2',
    name: 'Площадь Мужества',
    color: '#cf0000',
    ids: [171],
  },
  {
    region: '1',
    name: 'Площадь Революции',
    color: '#0572b9',
    ids: [96],
  },
  {
    region: '1',
    name: 'Площадь трёх вокзалов',
    color: '#f2bbe6',
    ids: [441, 518],
  },
  {
    region: '4777',
    name: 'Площадь Тукая',
    color: '#cf0000',
    ids: [318],
  },
  {
    region: '1',
    name: 'Плющево',
    color: '#d96835',
    ids: [475],
  },
  {
    region: '1',
    name: 'Победа',
    color: '#41b384',
    ids: [495],
  },
  {
    region: '1',
    name: 'Подольск',
    color: '#f2bbe6',
    ids: [436],
  },
  {
    region: '1',
    name: 'Подрезково',
    color: '#d96835',
    ids: [458],
  },
  {
    region: '1',
    name: 'Поклонная',
    color: '#41b384',
    ids: [510],
  },
  {
    region: '1',
    name: 'Покровское',
    color: '#f2bbe6',
    ids: [431],
  },
  {
    region: '1',
    name: 'Полежаевская',
    color: '#943f90',
    ids: [97],
  },
  {
    region: '2',
    name: 'Политехническая',
    color: '#cf0000',
    ids: [170],
  },
  {
    region: '1',
    name: 'Полянка',
    color: '#adacac',
    ids: [98],
  },
  {
    region: '1',
    name: 'Потапово',
    color: '#e42518',
    ids: [538],
  },
  {
    region: '1',
    name: 'Пражская',
    color: '#adacac',
    ids: [99],
  },
  {
    region: '1',
    name: 'Преображенская площадь',
    color: '#e42518',
    ids: [100],
  },
  {
    region: '2',
    name: 'Приморская',
    color: '#00701a',
    ids: [204],
  },
  {
    region: '1',
    name: 'Прокшино',
    color: '#e42518',
    ids: [378],
  },
  {
    region: '1',
    name: 'Пролетарская',
    color: '#943f90',
    ids: [101],
  },
  {
    region: '2',
    name: 'Пролетарская',
    color: '#00701a',
    ids: [212],
  },
  {
    region: '2',
    name: 'Проспект Большевиков',
    color: '#ff7f00',
    ids: [226],
  },
  {
    region: '1',
    name: 'Проспект Вернадского',
    color: '#78c7c9',
    ids: [450, 102],
  },
  {
    region: '2',
    name: 'Проспект Ветеранов',
    color: '#cf0000',
    ids: [185],
  },
  {
    region: '1',
    name: 'Проспект Мира',
    color: '#925233',
    ids: [103],
  },
  {
    region: '4777',
    name: 'Проспект Победы',
    color: '#cf0000',
    ids: [322],
  },
  {
    region: '2',
    name: 'Проспект Просвещения',
    color: '#03238b',
    ids: [187],
  },
  {
    region: '2',
    name: 'Проспект Славы',
    color: '#94007c',
    ids: [357],
  },
  {
    region: '1',
    name: 'Профсоюзная',
    color: '#ef7e24',
    ids: [104],
  },
  {
    region: '1',
    name: 'Пушкинская',
    color: '#943f90',
    ids: [105],
  },
  {
    region: '2',
    name: 'Пушкинская',
    color: '#cf0000',
    ids: [178],
  },
  {
    region: '1',
    name: 'Пыхтино',
    color: '#ffcd1e',
    ids: [536],
  },
  {
    region: '1',
    name: 'Пятницкое шоссе',
    color: '#0572b9',
    ids: [244],
  },
  {
    region: '1',
    name: 'Рабочий Посёлок',
    color: '#ffcd6f',
    ids: [401],
  },
  {
    region: '1',
    name: 'Раменки',
    color: '#ffcd1e',
    ids: [339],
  },
  {
    region: '1',
    name: 'Раменское',
    color: '#d96835',
    ids: [492],
  },
  {
    region: '1',
    name: 'Рассказовка',
    color: '#ffcd1e',
    ids: [367],
  },
  {
    region: '1',
    name: 'Реутов',
    color: '#41b384',
    ids: [531],
  },
  {
    region: '1',
    name: 'Речной вокзал',
    color: '#4baf4f',
    ids: [106],
  },
  {
    region: '1',
    name: 'Рижская',
    color: '#f2bbe6',
    ids: [107, 384, 517],
  },
  {
    region: '1',
    name: 'Римская',
    color: '#bed12e',
    ids: [108],
  },
  {
    region: '1',
    name: 'Ростокино',
    color: '#ffc8c8',
    ids: [297],
  },
  {
    region: '1',
    name: 'Румянцево',
    color: '#e42518',
    ids: [284],
  },
  {
    region: '2',
    name: 'Рыбацкое',
    color: '#00701a',
    ids: [214],
  },
  {
    region: '1',
    name: 'Рязанский проспект',
    color: '#943f90',
    ids: [109],
  },
  {
    region: '1',
    name: 'Савёловская',
    color: '#ffcd6f',
    ids: [110, 451, 515],
  },
  {
    region: '2',
    name: 'Садовая',
    color: '#94007c',
    ids: [220],
  },
  {
    region: '1',
    name: 'Саларьево',
    color: '#e42518',
    ids: [285],
  },
  {
    region: '1',
    name: 'Салтыковская',
    color: '#41b384',
    ids: [527],
  },
  {
    region: '1',
    name: 'Санино',
    color: '#41b384',
    ids: [497],
  },
  {
    region: '1',
    name: 'Свиблово',
    color: '#ef7e24',
    ids: [111],
  },
  {
    region: '1',
    name: 'Севастопольская',
    color: '#adacac',
    ids: [112],
  },
  {
    region: '4777',
    name: 'Северный вокзал',
    color: '#cf0000',
    ids: [314],
  },
  {
    region: '1',
    name: 'Селигерская',
    color: '#bed12e',
    ids: [354],
  },
  {
    region: '1',
    name: 'Семёновская',
    color: '#0572b9',
    ids: [113],
  },
  {
    region: '2',
    name: 'Сенная площадь',
    color: '#03238b',
    ids: [195],
  },
  {
    region: '1',
    name: 'Серп и Молот',
    color: '#41b384',
    ids: [520],
  },
  {
    region: '1',
    name: 'Серпуховская',
    color: '#adacac',
    ids: [114],
  },
  {
    region: '1',
    name: 'Сетунь',
    color: '#ffcd6f',
    ids: [402],
  },
  {
    region: '1',
    name: 'Силикатная',
    color: '#f2bbe6',
    ids: [435],
  },
  {
    region: '1',
    name: 'Сколково',
    color: '#ffcd6f',
    ids: [404],
  },
  {
    region: '1',
    name: 'Славянский бульвар',
    color: '#ffcd6f',
    ids: [229],
  },
  {
    region: '1',
    name: 'Смоленская',
    color: '#24bcef',
    ids: [115],
  },
  {
    region: '1',
    name: 'Сокол',
    color: '#4baf4f',
    ids: [116],
  },
  {
    region: '1',
    name: 'Соколиная Гора',
    color: '#ffc8c8',
    ids: [301],
  },
  {
    region: '1',
    name: 'Сокольники',
    color: '#78c7c9',
    ids: [385, 117],
  },
  {
    region: '1',
    name: 'Солнечная',
    color: '#41b384',
    ids: [504],
  },
  {
    region: '1',
    name: 'Солнцево',
    color: '#ffcd1e',
    ids: [364],
  },
  {
    region: '1',
    name: 'Сортировочная',
    color: '#d96835',
    ids: [471],
  },
  {
    region: '1',
    name: 'Спартак',
    color: '#943f90',
    ids: [275],
  },
  {
    region: '2',
    name: 'Спасская',
    color: '#ff7f00',
    ids: [232],
  },
  {
    region: '1',
    name: 'Спортивная',
    color: '#e42518',
    ids: [118],
  },
  {
    region: '2',
    name: 'Спортивная',
    color: '#94007c',
    ids: [219],
  },
  {
    region: '1',
    name: 'Сретенский бульвар',
    color: '#bed12e',
    ids: [119],
  },
  {
    region: '2',
    name: 'Старая Деревня',
    color: '#94007c',
    ids: [216],
  },
  {
    region: '1',
    name: 'Стахановская',
    color: '#d68ab1',
    ids: [376],
  },
  {
    region: '1',
    name: 'Стрешнево',
    color: '#f2bbe6',
    ids: [292],
  },
  {
    region: '1',
    name: 'Строгино',
    color: '#0572b9',
    ids: [228],
  },
  {
    region: '1',
    name: 'Студенческая',
    color: '#24bcef',
    ids: [120],
  },
  {
    region: '4777',
    name: 'Суконная слобода',
    color: '#cf0000',
    ids: [319],
  },
  {
    region: '1',
    name: 'Сухаревская',
    color: '#ef7e24',
    ids: [121],
  },
  {
    region: '1',
    name: 'Сходненская',
    color: '#943f90',
    ids: [122],
  },
  {
    region: '1',
    name: 'Сходня',
    color: '#d96835',
    ids: [457],
  },
  {
    region: '1',
    name: 'Таганская',
    color: '#943f90',
    ids: [123],
  },
  {
    region: '1',
    name: 'Тверская',
    color: '#4baf4f',
    ids: [124],
  },
  {
    region: '1',
    name: 'Театральная',
    color: '#4baf4f',
    ids: [125],
  },
  {
    region: '1',
    name: 'Текстильщики',
    color: '#f2bbe6',
    ids: [126, 452],
  },
  {
    region: '1',
    name: 'Телецентр',
    color: '#0a72b9',
    ids: [279],
  },
  {
    region: '1',
    name: 'Тёплый Стан',
    color: '#ef7e24',
    ids: [127],
  },
  {
    region: '1',
    name: 'Терехово',
    color: '#78c7c9',
    ids: [396],
  },
  {
    region: '1',
    name: 'Тестовская',
    color: '#ffcd6f',
    ids: [400, 512],
  },
  {
    region: '2',
    name: 'Технологический институт',
    color: '#cf0000',
    ids: [179],
  },
  {
    region: '1',
    name: 'Технопарк',
    color: '#4baf4f',
    ids: [283],
  },
  {
    region: '1',
    name: 'Тимирязевская',
    color: '#ffcd6f',
    ids: [128],
  },
  {
    region: '1',
    name: 'Толстопальцево',
    color: '#41b384',
    ids: [499],
  },
  {
    region: '1',
    name: 'Томилино',
    color: '#d96835',
    ids: [482],
  },
  {
    region: '1',
    name: 'Третьяковская',
    color: '#ef7e24',
    ids: [129],
  },
  {
    region: '1',
    name: 'Трикотажная',
    color: '#f2bbe6',
    ids: [421],
  },
  {
    region: '1',
    name: 'Тропарёво',
    color: '#e42518',
    ids: [281],
  },
  {
    region: '1',
    name: 'Трубная',
    color: '#bed12e',
    ids: [130],
  },
  {
    region: '1',
    name: 'Тульская',
    color: '#adacac',
    ids: [131],
  },
  {
    region: '1',
    name: 'Тургеневская',
    color: '#ef7e24',
    ids: [132],
  },
  {
    region: '1',
    name: 'Тушинская',
    color: '#f2bbe6',
    ids: [133],
  },
  {
    region: '1',
    name: 'Тютчевская',
    color: '#33735e',
    ids: [543],
  },
  {
    region: '1',
    name: 'Угрешская',
    color: '#ffc8c8',
    ids: [305],
  },
  {
    region: '1',
    name: 'Удельная',
    color: '#d96835',
    ids: [485],
  },
  {
    region: '2',
    name: 'Удельная',
    color: '#03238b',
    ids: [189],
  },
  {
    region: '1',
    name: 'Улица 1905 года',
    color: '#943f90',
    ids: [134],
  },
  {
    region: '1',
    name: 'Улица Академика Королёва',
    color: '#0a72b9',
    ids: [278],
  },
  {
    region: '1',
    name: 'Улица Академика Янгеля',
    color: '#adacac',
    ids: [135],
  },
  {
    region: '1',
    name: 'Улица Горчакова',
    color: '#bac8e8',
    ids: [136],
  },
  {
    region: '1',
    name: 'Улица Дмитриевского',
    color: '#d68ab1',
    ids: [371],
  },
  {
    region: '2',
    name: 'Улица Дыбенко',
    color: '#ff7f00',
    ids: [227],
  },
  {
    region: '1',
    name: 'Улица Милашенкова',
    color: '#0a72b9',
    ids: [280],
  },
  {
    region: '1',
    name: 'Улица Сергея Эйзенштейна',
    color: '#0a72b9',
    ids: [276],
  },
  {
    region: '1',
    name: 'Улица Скобелевская',
    color: '#bac8e8',
    ids: [138],
  },
  {
    region: '1',
    name: 'Улица Старокачаловская',
    color: '#bac8e8',
    ids: [139],
  },
  {
    region: '1',
    name: 'Университет',
    color: '#e42518',
    ids: [140],
  },
  {
    region: '1',
    name: 'Университет Дружбы Народов',
    color: '#33735e',
    ids: [549],
  },
  {
    region: '1',
    name: 'Ухтомская',
    color: '#d96835',
    ids: [479],
  },
  {
    region: '1',
    name: 'Фабричная',
    color: '#d96835',
    ids: [491],
  },
  {
    region: '1',
    name: 'Физтех',
    color: '#bed12e',
    ids: [533],
  },
  {
    region: '1',
    name: 'Филатов Луг',
    color: '#e42518',
    ids: [377],
  },
  {
    region: '1',
    name: 'Филёвский парк',
    color: '#24bcef',
    ids: [141],
  },
  {
    region: '1',
    name: 'Фили',
    color: '#ffcd6f',
    ids: [142],
  },
  {
    region: '1',
    name: 'Фирсановская',
    color: '#d96835',
    ids: [456],
  },
  {
    region: '1',
    name: 'Фонвизинская',
    color: '#bed12e',
    ids: [286],
  },
  {
    region: '1',
    name: 'Фрунзенская',
    color: '#e42518',
    ids: [143],
  },
  {
    region: '2',
    name: 'Фрунзенская',
    color: '#03238b',
    ids: [197],
  },
  {
    region: '1',
    name: 'Химки',
    color: '#d96835',
    ids: [461],
  },
  {
    region: '1',
    name: 'Хлебниково',
    color: '#ffcd6f',
    ids: [408],
  },
  {
    region: '1',
    name: 'Ховрино',
    color: '#d96835',
    ids: [463, 349],
  },
  {
    region: '1',
    name: 'Хорошёво',
    color: '#ffc8c8',
    ids: [289],
  },
  {
    region: '1',
    name: 'Хорошёвская',
    color: '#78c7c9',
    ids: [351],
  },
  {
    region: '1',
    name: 'Царицыно',
    color: '#f2bbe6',
    ids: [144],
  },
  {
    region: '1',
    name: 'Цветной бульвар',
    color: '#adacac',
    ids: [145],
  },
  {
    region: '1',
    name: 'ЦСКА',
    color: '#78c7c9',
    ids: [352],
  },
  {
    region: '1',
    name: 'Черкизовская',
    color: '#e42518',
    ids: [146],
  },
  {
    region: '2',
    name: 'Черная речка',
    color: '#03238b',
    ids: [191],
  },
  {
    region: '2',
    name: 'Чернышевская',
    color: '#cf0000',
    ids: [175],
  },
  {
    region: '1',
    name: 'Чертановская',
    color: '#adacac',
    ids: [147],
  },
  {
    region: '1',
    name: 'Чеховская',
    color: '#adacac',
    ids: [148],
  },
  {
    region: '1',
    name: 'Чистые пруды',
    color: '#e42518',
    ids: [149],
  },
  {
    region: '1',
    name: 'Чкаловская',
    color: '#bed12e',
    ids: [150],
  },
  {
    region: '2',
    name: 'Чкаловская',
    color: '#94007c',
    ids: [218],
  },
  {
    region: '1',
    name: 'Чухлинка',
    color: '#41b384',
    ids: [522],
  },
  {
    region: '1',
    name: 'Шаболовская',
    color: '#ef7e24',
    ids: [151],
  },
  {
    region: '1',
    name: 'Шелепиха',
    color: '#78c7c9',
    ids: [453, 311],
  },
  {
    region: '1',
    name: 'Шереметьевская',
    color: '#ffcd6f',
    ids: [383],
  },
  {
    region: '1',
    name: 'Шипиловская',
    color: '#bed12e',
    ids: [238],
  },
  {
    region: '1',
    name: 'Шоссе Энтузиастов',
    color: '#ffc8c8',
    ids: [152],
  },
  {
    region: '2',
    name: 'Шушары',
    color: '#94007c',
    ids: [359],
  },
  {
    region: '1',
    name: 'Щёлковская',
    color: '#0572b9',
    ids: [153],
  },
  {
    region: '1',
    name: 'Щербинка',
    color: '#f2bbe6',
    ids: [434],
  },
  {
    region: '1',
    name: 'Щукинская',
    color: '#f2bbe6',
    ids: [154],
  },
  {
    region: '1',
    name: 'Электрозаводская',
    color: '#d96835',
    ids: [470, 386, 155],
  },
  {
    region: '2',
    name: 'Электросила',
    color: '#03238b',
    ids: [199],
  },
  {
    region: '1',
    name: 'Юго-Восточная',
    color: '#d68ab1',
    ids: [374],
  },
  {
    region: '1',
    name: 'Юго-Западная',
    color: '#e42518',
    ids: [156],
  },
  {
    region: '1',
    name: 'Южная',
    color: '#adacac',
    ids: [157],
  },
  {
    region: '1',
    name: 'Ясенево',
    color: '#ef7e24',
    ids: [158],
  },
  {
    region: '1',
    name: 'Яхромская',
    color: '#bed12e',
    ids: [398],
  },
  {
    region: '4777',
    name: 'Яшьлек',
    color: '#cf0000',
    ids: [315],
  },
];
